package com.xuekun.electricEquipment.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table company
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Company {
    /**
     * Database Column Remarks:
     *   公司编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * Database Column Remarks:
     *   公司名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * Database Column Remarks:
     *   公司介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_introduce
     *
     * @mbggenerated
     */
    private String companyIntroduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_id
     *
     * @return the value of company.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_id
     *
     * @param companyId the value for company.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param companyName the value for company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_introduce
     *
     * @return the value of company.company_introduce
     *
     * @mbggenerated
     */
    public String getCompanyIntroduce() {
        return companyIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_introduce
     *
     * @param companyIntroduce the value for company.company_introduce
     *
     * @mbggenerated
     */
    public void setCompanyIntroduce(String companyIntroduce) {
        this.companyIntroduce = companyIntroduce;
    }
}