package com.xuekun.electricEquipment.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table news
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class News {
    /**
     * Database Column Remarks:
     *   新闻编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated
     */
    private Integer newsId;

    /**
     * Database Column Remarks:
     *   新闻标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbggenerated
     */
    private String newsTitle;

    /**
     * Database Column Remarks:
     *   新闻内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.new_content
     *
     * @mbggenerated
     */
    private String newContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbggenerated
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbggenerated
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.new_content
     *
     * @return the value of news.new_content
     *
     * @mbggenerated
     */
    public String getNewContent() {
        return newContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.new_content
     *
     * @param newContent the value for news.new_content
     *
     * @mbggenerated
     */
    public void setNewContent(String newContent) {
        this.newContent = newContent;
    }
}