package com.xuekun.electricEquipment.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Product {
    /**
     * Database Column Remarks:
     *   产品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   产品类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type_name
     *
     * @mbggenerated
     */
    private String productTypeName;

    /**
     * Database Column Remarks:
     *   产品类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbggenerated
     */
    private Integer productType;

    /**
     * Database Column Remarks:
     *   产品用途
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_purpose
     *
     * @mbggenerated
     */
    private String productPurpose;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   产品图片二进制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_image
     *
     * @mbggenerated
     */
    private String productImage;

    /**
     * Database Column Remarks:
     *   产品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_desc
     *
     * @mbggenerated
     */
    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type_name
     *
     * @return the value of product.product_type_name
     *
     * @mbggenerated
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type_name
     *
     * @param productTypeName the value for product.product_type_name
     *
     * @mbggenerated
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbggenerated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbggenerated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_purpose
     *
     * @return the value of product.product_purpose
     *
     * @mbggenerated
     */
    public String getProductPurpose() {
        return productPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_purpose
     *
     * @param productPurpose the value for product.product_purpose
     *
     * @mbggenerated
     */
    public void setProductPurpose(String productPurpose) {
        this.productPurpose = productPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_image
     *
     * @return the value of product.product_image
     *
     * @mbggenerated
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_image
     *
     * @param productImage the value for product.product_image
     *
     * @mbggenerated
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_desc
     *
     * @return the value of product.product_desc
     *
     * @mbggenerated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_desc
     *
     * @param productDesc the value for product.product_desc
     *
     * @mbggenerated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
}